# Generated by Django 5.0.6 on 2026-03-21 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ugx', models.DecimalField(decimal_places=2, max_digits=14)),
                ('purpose', models.TextField(help_text='What the distribution is for')),
                ('beneficiaries', models.TextField(help_text='JSON list of beneficiary artisans')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='proposed', max_length=20)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('craft_tradition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='artisans.crafttradition')),
            ],
        ),
        migrations.CreateModel(
            name='HeritageFundEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('contribution', 'Contribution'), ('distribution', 'Distribution')], max_length=20)),
                ('amount_ugx', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('craft_tradition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heritage_entries', to='artisans.crafttradition')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heritage_entries', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Heritage Fund Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
