# Generated by Django 5.1.4 on 2026-06-06 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_artisan_artisans_ar_user_id_a8f436_idx_and_more'),
        ('heritage', '0001_initial'),
        ('orders', '0002_order_buyer_email_order_buyer_phone_returnrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['craft_tradition'], name='heritage_di_craft_t_209535_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['status'], name='heritage_di_status_f2c19c_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['-created_at'], name='heritage_di_created_b96588_idx'),
        ),
        migrations.AddIndex(
            model_name='heritagefundentry',
            index=models.Index(fields=['order'], name='heritage_he_order_i_d85a03_idx'),
        ),
        migrations.AddIndex(
            model_name='heritagefundentry',
            index=models.Index(fields=['craft_tradition'], name='heritage_he_craft_t_5bcf8f_idx'),
        ),
        migrations.AddIndex(
            model_name='heritagefundentry',
            index=models.Index(fields=['entry_type'], name='heritage_he_entry_t_f0e5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='heritagefundentry',
            index=models.Index(fields=['-created_at'], name='heritage_he_created_28dbe8_idx'),
        ),
    ]
