# Generated by Django 5.0.6 on 2026-03-21 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
        ('gifting', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid - Awaiting Artisan Confirmation'), ('confirmed', 'Artisan Confirmed'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], default='pending_payment', max_length=30)),
                ('payout_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_gift', models.BooleanField(default=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('price_ugx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('artisan_earnings_ugx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_commission_ugx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('heritage_fund_ugx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('momo', 'MTN MoMo'), ('airtel', 'Airtel Money'), ('ton', 'TON Crypto')], max_length=10)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('shipping_name', models.CharField(max_length=200)),
                ('shipping_address', models.JSONField(help_text='{line1, city, country, postcode}')),
                ('shipping_country', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('dispatch_photo', models.ImageField(blank=True, upload_to='orders/dispatch/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_artisan', to='artisans.artisan')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('gift_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='gifting.giftdetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
