# Generated by Django 5.1.4 on 2026-03-31 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('damaged', 'Damaged'), ('wrong_item', 'Wrong Item'), ('not_as_described', 'Not As Described'), ('late_delivery', 'Late Delivery'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='requested', max_length=20)),
                ('refund_amount_ugx', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
