# Generated by Django 5.1.4 on 2026-06-06 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_artisan_artisans_ar_user_id_a8f436_idx_and_more'),
        ('gifting', '0003_giftorder_gifting_workflow_fields'),
        ('orders', '0002_order_buyer_email_order_buyer_phone_returnrequest'),
        ('products', '0003_product_products_pr_artisan_445201_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer'], name='orders_orde_buyer_i_90aa29_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['artisan'], name='orders_orde_artisan_991a51_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method'], name='orders_orde_payment_63e120_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product'], name='orders_orde_product_cacc30_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payout_status'], name='orders_orde_payout__9e12d6_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order'], name='orders_retu_order_i_359730_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status'], name='orders_retu_status_1e9e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['-created_at'], name='orders_retu_created_c78331_idx'),
        ),
    ]
