# Generated by Django 5.1.4 on 2026-06-06 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('otp_requested', 'OTP Requested'), ('otp_verified', 'OTP Verified'), ('totp_setup', '2FA Setup'), ('totp_verified', '2FA Verified'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('settings_changed', 'Settings Changed'), ('payment_approved', 'Payment Approved'), ('order_updated', 'Order Updated')], db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'db_table': 'accounts_admin_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_ad_user_id_5a1e34_idx'), models.Index(fields=['action', '-created_at'], name='accounts_ad_action_e219ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('otp_verified', models.BooleanField(default=False)),
                ('totp_secret', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('totp_verified', models.BooleanField(default=False)),
                ('totp_backup_codes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Session',
                'verbose_name_plural': 'Admin Sessions',
                'db_table': 'accounts_admin_session',
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_ad_user_id_bcf2f1_idx'), models.Index(fields=['totp_verified'], name='accounts_ad_totp_ve_db5164_idx')],
            },
        ),
    ]
