# Generated by Django 5.0.6 on 2026-03-21 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='JSON list of requirements')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CraftTradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_luganda', models.CharField(blank=True, max_length=200)),
                ('ethnic_group', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Cultural context and history')),
                ('gi_status', models.CharField(choices=[('none', 'None'), ('pending', 'GI Pending'), ('registered', 'GI Registered')], default='none', max_length=20)),
                ('heritage_fund_levy_pct', models.DecimalField(decimal_places=2, default=3.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Craft Traditions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('bio', models.TextField(help_text='Written in artisan voice')),
                ('bio_luganda', models.TextField(blank=True)),
                ('bio_swahili', models.TextField(blank=True)),
                ('bio_draft', models.TextField(blank=True, null=True)),
                ('bio_draft_language', models.CharField(blank=True, max_length=10)),
                ('bio_draft_at', models.DateTimeField(blank=True, null=True)),
                ('community', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('momo_number', models.CharField(blank=True, max_length=20)),
                ('airtel_number', models.CharField(blank=True, max_length=20)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('is_certified', models.BooleanField(default=False)),
                ('onboarded_via', models.CharField(choices=[('web', 'Web Form'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram Bot'), ('field', 'Field Officer')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_photo', models.ImageField(blank=True, upload_to='artisans/profiles/')),
                ('cover_photo', models.ImageField(blank=True, upload_to='artisans/covers/')),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artisan', to=settings.AUTH_USER_MODEL)),
                ('certifications', models.ManyToManyField(blank=True, related_name='artisans', to='artisans.certification')),
                ('craft_tradition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artisans', to='artisans.crafttradition')),
            ],
            options={
                'verbose_name_plural': 'Artisans',
                'ordering': ['-created_at'],
            },
        ),
    ]
