# Generated by Django 5.1.4 on 2026-06-06 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artisan',
            index=models.Index(fields=['user'], name='artisans_ar_user_id_a8f436_idx'),
        ),
        migrations.AddIndex(
            model_name='artisan',
            index=models.Index(fields=['is_active'], name='artisans_ar_is_acti_c32775_idx'),
        ),
        migrations.AddIndex(
            model_name='artisan',
            index=models.Index(fields=['is_certified'], name='artisans_ar_is_cert_5c2951_idx'),
        ),
        migrations.AddIndex(
            model_name='artisan',
            index=models.Index(fields=['-created_at'], name='artisans_ar_created_175b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='artisan',
            index=models.Index(fields=['craft_tradition'], name='artisans_ar_craft_t_d03ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='artisan',
            index=models.Index(fields=['district'], name='artisans_ar_distric_0a2456_idx'),
        ),
    ]
