# Generated by Django 5.1.4 on 2026-03-31 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_buyer_email_order_buyer_phone_returnrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('momo', 'MTN MoMo'), ('airtel', 'Airtel Money'), ('ton', 'TON Crypto'), ('manual', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('external_reference', models.CharField(blank=True, max_length=200)),
                ('amount_ugx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=8)),
                ('checkout_url', models.URLField(blank=True)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
