# Generated by Django 5.1.4 on 2026-06-06 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_artisan_artisans_ar_user_id_a8f436_idx_and_more'),
        ('orders', '0003_order_orders_orde_buyer_i_90aa29_idx_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ugx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('to_account', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='artisans.artisan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='payments_pa_order_i_01d68f_idx'), models.Index(fields=['artisan'], name='payments_pa_artisan_2f46c2_idx'), models.Index(fields=['status'], name='payments_pa_status_d49350_idx'), models.Index(fields=['-created_at'], name='payments_pa_created_61eb0f_idx')],
            },
        ),
    ]
