# Generated by Django 5.0.6 on 2026-03-21 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('name_luganda', models.CharField(blank=True, max_length=300)),
                ('story', models.TextField(help_text='Artisan narrative - from voice note or written')),
                ('story_luganda', models.TextField(blank=True)),
                ('story_swahili', models.TextField(blank=True)),
                ('story_draft', models.TextField(blank=True, null=True)),
                ('story_draft_language', models.CharField(blank=True, max_length=10)),
                ('story_draft_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.CharField(help_text='e.g., Natural sisal from family land', max_length=300)),
                ('technique', models.CharField(help_text='e.g., Kiganda coiling - 3-strand plait', max_length=400)),
                ('days_to_make', models.PositiveSmallIntegerField(default=1)),
                ('price_ugx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('artisan_pct', models.DecimalField(decimal_places=2, default=85.0, max_digits=4)),
                ('heritage_pct', models.DecimalField(decimal_places=2, default=3.0, max_digits=4)),
                ('platform_pct', models.DecimalField(decimal_places=2, default=12.0, max_digits=4)),
                ('stock', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold_out', 'Sold Out'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_customisable', models.BooleanField(default=False)),
                ('weight_grams', models.PositiveIntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='artisans.artisan')),
                ('craft_tradition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artisans.crafttradition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/photos/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('is_hero', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', '-is_hero'],
            },
        ),
        migrations.CreateModel(
            name='ProvenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artisan_name', models.CharField(max_length=200)),
                ('community', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('craft_tradition', models.CharField(max_length=200)),
                ('ethnic_group', models.CharField(max_length=100)),
                ('technique_detail', models.TextField()),
                ('material_source', models.CharField(max_length=300)),
                ('gi_status', models.CharField(max_length=20)),
                ('record_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Provenance Records',
            },
        ),
    ]
