# Generated by Django 5.1.4 on 2026-05-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
