# Generated by Django 5.1.4 on 2026-06-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_artisan_artisans_ar_user_id_a8f436_idx_and_more'),
        ('products', '0002_alter_product_embedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['artisan'], name='products_pr_artisan_445201_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['craft_tradition'], name='products_pr_craft_t_30a7c0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
    ]
