# Generated by Django 5.0.6 on 2026-03-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_relationship', models.CharField(help_text='e.g., Mother, Friend, Colleague', max_length=100)),
                ('occasion', models.CharField(choices=[('birthday', 'Birthday'), ('wedding', 'Wedding'), ('graduation', 'Graduation'), ('baby_shower', 'Baby Shower'), ('thank_you', 'Saying Thank You'), ('cultural', 'Cultural Celebration'), ('just_because', 'Just Because')], max_length=20)),
                ('personal_message', models.TextField(help_text='Printed on handwritten-style card', max_length=500)),
                ('gift_wrap', models.BooleanField(default=True)),
                ('scheduled_delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('total_amount_ugx', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gift Orders',
            },
        ),
    ]
