# Generated by Django 5.1.4 on 2026-03-31 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_ugx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total_ugx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gifting.giftorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_order_items', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
